# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j01G5Of0RwXSF1DQKZcVp8OAwrKq8QiH
"""

from google.colab import files
data_to_load=files.upload()

import pandas as pd
import plotly.express as px
df=pd.read_csv("data.csv")
fig=px.scatter(df,
               x="date",
               y="cases", 
               color="country"
              )
fig.show()